# Generated by Django 4.2.3 on 2023-07-11 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('bio', models.TextField()),
                ('picture', models.ImageField(upload_to='page/picture')),
                ('is_organization', models.BooleanField(default=False)),
                ('wide_picture', models.ImageField(blank=True, null=True, upload_to='page/wide_picture/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('followed', models.BooleanField(default=False)),
                ('followers_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
